theme: minima
title: David Menezes Professional Portfolio
author: David M. Menezes
description: My personal webpage!
header_pages:
  - index.md
  - 2025-10-01-First-Blog-Post.md
  - 2025-10-01-Current-Research.md




